### ISSUE TITLE
Mount error while staring waydroid

### ISSUE THREAD

**Issue by Obnomus** [gmankab/waydroid#4]
I followed every instruction and getting mount error so I checked that I've enough permission and yes I got permission and system img is there too, I hope I can get help

![waydroid_error](https://github.com/user-attachments/assets/f7f0c815-4bed-4ba8-9198-b83abdcefcd4)

**Comment by Benjamin-Loison** [comment]
What is the line number of [gmankab/waydroid/blob/ff230959139efe413120496c99e3ac1c70a10a4a/readme.md?plain=1](https://github.com/gmankab/waydroid/blob/ff230959139efe413120496c99e3ac1c70a10a4a/readme.md?plain=1) that involves your error?
Furthermore, on what OS are you?

**Comment by Obnomus** [comment]
> What is the line number of [gmankab/waydroid/blob/ff230959139efe413120496c99e3ac1c70a10a4a/readme.md?plain=1](https://github.com/gmankab/waydroid/blob/ff230959139efe413120496c99e3ac1c70a10a4a/readme.md?plain=1) that involves your error? Furthermore, on what OS are you?

Nvm bro fixed it

**Comment by ghost** [comment]
How did you fix it? I have got the same issue

**Comment by Obnomus** [comment]
> How did you fix it? I have got the same issue

First install waydroid and then replace the Android 13 system and vendor imgs at 

> /etc/waydroid-extra/images/

And keep in mind that in A13 your apps won't be shown in your linux app list so you gotta make desktop entry for every app

**Comment by ghost** [comment]
I figured I had to change to that too, I even opened the pull request #5 to fix this issue.
